import pygame

import src.config as c
from src.utils import get_scale_from_y


class Bullet:
    def __init__(self, x, y, direction): ...

    def update(self): ...

    def _update_size(self): ...

    def draw(self, screen): ...

    def is_off_screen(self): ...
