import pygame

import src.config as c
from src.bullet import Bullet
from src.enemy import Enemy
from src.player import Player


class Game:
    def __init__(self): ...

    def run(self): ...

    def _handle_events(self): ...

    def _shoot(self): ...

    def _update(self): ...

    def _check_bullet_collision(self, enemy): ...

    def _spawn_enemies(self): ...

    def _draw(self): ...

    def _draw_ui(self): ...
